---
esphome:
  name: "esphome-${devicename}"

# Enable logging
logger:

# Home Assistant → nope
# api:

ota:
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "espHome ${devicename}"
    password: !secret hotspot_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  use_abbreviations: false
  topic_prefix: "espHome-${devicename}"
  log_topic:
    topic: "espHome-${devicename}/debug"
    retain: false

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

sensor:
  - <<: !include .sensors-base.yaml
