---
- platform: dht
  pin: D6
  model: DHT22
  update_interval: 10s
  temperature:
    name: "Temperature"
    accuracy_decimals: 3
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12 # 6 * 2min
          send_first_at: 6
  humidity:
    name: "Humidity"
    accuracy_decimals: 2
    filters:
      - lambda: if (x > 1.0 && x < 99.0) { return x; } else { return {}; }
      - exponential_moving_average:
          alpha: 0.05
          send_every: 24 # 6 * 4min
          send_first_at: 6
