---
- platform: dht
  pin: D6
  model: DHT22
  update_interval: 10s
  temperature:
    name: "Temperature"
    accuracy_decimals: 3
    filters:
      - exponential_moving_average:
          alpha: 0.05
          send_every: 1
      - heartbeat: 2min
  humidity:
    name: "Humidity"
    accuracy_decimals: 2
    filters:
      - exponential_moving_average:
          alpha: 0.05
          send_every: 1
      - heartbeat: 4min
