---
esphome:
  name: esphome-${devicename}

# Enable logging
logger:
  # level: DEBUG # default
  # level: INFO # use for battery operated devices
  # level: VERBOSE # use to understand problems?

# Home Assistant → nope
# api:

ota:
  - platform: web_server
  - platform: esphome
    password: !secret ota_password

network:
  enable_ipv6: true

wifi:
  # when updating from another name use the ip / hostname for connection
  #use_address: 192.168.178.666
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: espHome ${devicename}
    password: !secret hotspot_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery_unique_id_generator: mac
  use_abbreviations: false
  topic_prefix: espHome-${devicename}
  log_topic:
    topic: espHome-${devicename}/debug
    retain: false

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

sensor:
  - platform: wifi_signal
    name: RSSI
    update_interval: 10s
    accuracy_decimals: 2
    filters:
      - lambda: if (x < 0.0) { return x; } else { return {}; }
      - exponential_moving_average:
          alpha: 0.05
          send_every: 24 # 6 * 4min
          send_first_at: 6
