---
<<: !include .nodemcuv2-i2c.yaml

substitutions:
  devicename: booksolar
  tcs_gain: 4x

sensor:
  - !include .sensor-wifi-signal.yaml
  - !include .sensor-nodemcuv2-dht.yaml
  - !include .sensor-tcs34725.yaml
