# see https://esphome.io/components/sensor/scd30.html
---
<<: !include .nodemcuv2.yaml

substitutions:
  devicename: co2

sensor:
  - <<: !include .base-sensors.yaml
  - platform: scd30
    update_interval: 30s
    co2:
      name: "CO2"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            send_every: 4 # 2 times per min * 2 min
    temperature:
      name: "Temperature"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            send_every: 4 # 2 times per min * 2 min
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            send_every: 10 # 2 times per min * 5 min
