# see https://esphome.io/components/sensor/scd30.html
---
<<: !include .nodemcuv2.yaml

substitutions:
  devicename: co2

sensor:
  - <<: !include .sensors-base.yaml
  - platform: scd30
    update_interval: 30s
    co2:
      name: "CO2"
      accuracy_decimals: 1
      filters:
        - filter_out: 0.0
        - throttle_average: 2min
        - filter_out: nan
    temperature:
      name: "Temperature"
      accuracy_decimals: 2
      filters:
        - throttle_average: 2min
        - filter_out: nan
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
      filters:
        - throttle_average: 5min
        - filter_out: nan
