# see https://esphome.io/components/sensor/scd30.html
---
<<: !include .nodemcuv2.yaml

substitutions:
  devicename: co2

sensor:
  - <<: !include .sensors-base.yaml
  - platform: scd30
    update_interval: 30s
    co2:
      name: "CO2"
      accuracy_decimals: 1
      filters:
        - filter_out: 0.0
        - exponential_moving_average:
            alpha: 0.2
            send_every: 1
        - heartbeat: 2min
    temperature:
      name: "Temperature"
      accuracy_decimals: 3
      filters:
        - exponential_moving_average:
            alpha: 0.2
            send_every: 1
        - heartbeat: 2min
    humidity:
      name: "Humidity"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.2
            send_every: 1
        - heartbeat: 4min
