---
<<: !include .nodemcuv2.yaml

substitutions:
  devicename: klingelschrank

sensor:
  - !include .sensor-wifi-signal.yaml
  - !include .sensor-nodemcuv2-dht22.yaml

binary_sensor:
  - !include .binary-sensor-status.yaml
  - platform: gpio
    name: Klingel
    pin:
      number: D2 # connect the other end to GND
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 100ms
