# update the devicename or run via
# esphome -s devicename test run nodemcuv2-dht.yaml
---
<<: !include .nodemcuv2.yaml

substitutions:
  devicename: dht-default

sensor:
  - !include .sensor-wifi-signal.yaml
  - !include .sensor-nodemcuv2-dht.yaml
